version: "2.2"
volumes:
    dbdata:
services:
    builder:
        build: ./frontend
        volumes:
            - ./frontend/src:/var/frontend/src
            - ./backend/static:/var/frontend/output
    www:
        build: ./backend
        ports:
            - 80:8000
        links:
            - db:db
        volumes:
            - ./backend:/var/app
    db:
        build: ./db
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: django
        volumes:
            - dbdata:/var/lib/postgresql/data
