version: "2.2"
volumes:
    dbdata:
    certificates:
services:
    builder:
        build: ./frontend
        volumes:
            - ./frontend/src:/var/frontend/src
            - ./backend/static:/var/frontend/output
    manual:
        build: ./backend
        environment:
            SITE_ID: 2
        links:
            - db:db
        volumes:
            - ./backend:/var/app
    www:
        build: ./backend
        environment:
            SITE_ID: 1
        links:
            - db:db
        volumes:
            - ./backend:/var/app
    db:
        build: ./db
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: django
        volumes:
            - dbdata:/var/lib/postgresql/data

    nginx:
        build: ./nginx
        hostname: nginx
        volumes:
            - certificates:/etc/letsencrypt
        ports:
            - 80:80
        environment:
            ZETKIN_DOMAIN: localhost
        links:
            - www
            - manual
